<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE
        menuitems
        [
                <!ELEMENT menuitems (menuitem+)*>
                <!ELEMENT menuitem (menuitem*)*>
                <!ATTLIST menuitem
                        type CDATA "javax.swing.JMenuItem"
                        name CDATA #REQUIRED
                        mnemonic CDATA #IMPLIED
                        actionEnabled (true|false) "true"
                        separator (true|false) "false"
                        accelerator CDATA "#IMPLIED"
                        tooltip CDATA "Menu item"
                        icon CDATA #IMPLIED
                        actionCommand CDATA #IMPLIED
                        actionMode (true|false) "true"
                        toolButton CDATA #IMPLIED
                        toolButtonTextVisible (true|false) "false"
                        popup (true|false) "false"
                        popupSep (true|false) "false"
                        last (true|false) "false"
                        lastMenu (true|false) "false"
                        >
                ]>
<menuitems>
    <menuitem
            type="javax.swing.JMenu"
            name="FontMap"
            mnemonic="F"
    >
        <menuitem
                name="New"
                mnemonic="N"
                accelerator="control N"
                tooltip="Create a New FontMap"
                icon="images/new.png"
                actionCommand="New"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Open..."
                mnemonic="O"
                accelerator="control O"
                tooltip="Open Existing FontMap"
                icon="images/load.png"
                actionCommand="Open..."
                separator="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                type="javax.swing.JMenu"
                name="ReOpen"
                mnemonic="O"
                actionEnabled="false"
                separator="true"
        >
            <menuitem
                    name="Clear List"
                    tooltip="Clear the list of ReOpen FontMap"
                    actionCommand="ClearList"
                    separator="true"
                    last="true"
            />
        </menuitem>
        <menuitem
                name="Save"
                mnemonic="S"
                accelerator="control S"
                tooltip="Save FontMap"
                icon="images/save.png"
                actionCommand="Save"
                actionEnabled="false"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Save As..."
                mnemonic="A"
                tooltip="Save FontMap As"
                icon="images/saveas.png"
                actionCommand="Save As..."
                actionEnabled="false"
                separator="true"
        />
        <menuitem
                name="ReLoad from Disk"
                mnemonic="k"
                accelerator="control K"
                tooltip="ReLoad Existing FontMap"
                icon="images/reload.png"
                actionCommand="ReLoad"
                actionEnabled="false"
                separator="true"
        />
        <menuitem
                name="Close"
                mnemonic="C"
                accelerator="control F4"
                tooltip="Close FontMap"
                icon="images/close.png"
                actionCommand="Close"
                actionEnabled="false"
                separator="true"
        />
        <menuitem
                name="Exit"
                mnemonic="X"
                tooltip="Exit"
                actionCommand="Exit"
                last="true"
        />
    </menuitem>
    <menuitem
            type="javax.swing.JMenu"
            name="Edit"
            mnemonic="E"
    >
        <menuitem
                name="Undo"
                mnemonic="u"
                accelerator="control Z"
                tooltip="Undo Edit"
                icon="images/undo.png"
                actionEnabled="false"
                actionCommand="Undo"
                popup="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Redo"
                mnemonic="r"
                accelerator="control shift Z"
                tooltip="Redo Edit"
                icon="images/redo.png"
                actionEnabled="false"
                actionCommand="Redo"
                popupSep="true"
                separator="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Cut"
                mnemonic="t"
                accelerator="control X"
                tooltip="Cut Selected Mapping"
                icon="images/cut.png"
                actionCommand="Cut"
                actionEnabled="false"
                popup="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Copy"
                mnemonic="C"
                accelerator="control C"
                tooltip="Copy Selected Mapping"
                icon="images/copy.png"
                actionCommand="Copy"
                actionEnabled="false"
                popup="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Paste"
                mnemonic="P"
                accelerator="control V"
                tooltip="Paste"
                icon="images/paste.png"
                actionCommand="Paste"
                actionEnabled="false"
                popupSep="true"
                separator="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Select All"
                mnemonic="A"
                accelerator="control A"
                tooltip="Select All Mapping"
                actionCommand="Select All"
                actionEnabled="false"
                popupSep="true"
                separator="true"
        />
        <menuitem
                name="Delete"
                mnemonic="D"
                accelerator="DELETE"
                tooltip="Delete Selected Mapping"
                icon="images/delete.png"
                actionCommand="Delete"
                actionEnabled="false"
                popup="true"
                last="true"
        />
    </menuitem>
    <menuitem
            type="javax.swing.JMenu"
            name="Transliterate"
            mnemonic="T"
    >
        <menuitem
                name="Input"
                mnemonic="I"
                accelerator="control alt I"
                tooltip="Select Input file - source"
                icon="images/input.png"
                actionEnabled="false"
                actionCommand="Input"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Output"
                mnemonic="O"
                accelerator="control alt O"
                tooltip="Select Output file - target"
                icon="images/output.png"
                actionEnabled="false"
                actionCommand="Output"
                separator="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Convert"
                mnemonic="C"
                accelerator="control alt C"
                tooltip="Convert based on the current FontMap"
                icon="images/convert.png"
                actionCommand="Convert"
                actionEnabled="false"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="Stop"
                mnemonic="S"
                accelerator="control alt S"
                tooltip="Stop Conversion"
                icon="images/stop.png"
                actionCommand="Stop"
                actionEnabled="false"
                last="true"
                toolButton="javax.swing.JButton"
        />
    </menuitem>
    <menuitem
            type="javax.swing.JMenu"
            name="Options"
            mnemonic="O"
    >
        <menuitem
                name="Reverse Transliterate"
                type="javax.swing.JCheckBoxMenuItem"
                mnemonic="R"
                accelerator="control alt R"
                tooltip="Transliterate in Reverse direction"
                actionCommand="Reverse"
                actionMode="false"
                toolButton="javax.swing.JCheckBox"
                toolButtonTextVisible="true"
        />
        <menuitem
                name="Preserve &lt;Tags&gt;"
                type="javax.swing.JCheckBoxMenuItem"
                mnemonic="P"
                accelerator="control alt P"
                tooltip="Don't Transliterate words in tags"
                actionCommand="Preserve"
                actionMode="false"
                toolButton="javax.swing.JCheckBox"
                toolButtonTextVisible="true"
                separator="true"
        />
        <menuitem
                type="javax.swing.JMenu"
                name="Look &amp; Feel"
                mnemonic="L"
                last="true"
                lastMenu="true"
        />
    </menuitem>
    <menuitem
            type="javax.swing.JMenu"
            name="View"
            mnemonic="V"
    >
        <menuitem
                name="Toolbar"
                type="javax.swing.JCheckBoxMenuItem"
                mnemonic="T"
                accelerator="control shift T"
                tooltip="Show/Hide Toolbar"
                actionCommand="ViewTool"
        />
        <menuitem
                name="Status Bar"
                type="javax.swing.JCheckBoxMenuItem"
                mnemonic="S"
                accelerator="control shift S"
                tooltip="Show/Hide Status Bar"
                actionCommand="ViewStatus"
                separator="true"
        />
        <menuitem
                name="Mapping Rules"
                type="javax.swing.JCheckBoxMenuItem"
                mnemonic="M"
                accelerator="control shift M"
                tooltip="Show/Hide Mapping Details"
                actionCommand="ViewMapping"
                actionEnabled="false"
        />
        <menuitem
                name="Mapping Preview"
                type="javax.swing.JCheckBoxMenuItem"
                mnemonic="A"
                accelerator="control shift A"
                tooltip="Show/Hide Sample Text"
                actionCommand="ViewSample"
                actionEnabled="false"
                last="true"
        />
    </menuitem>
    <menuitem
            type="javax.swing.JMenu"
            name="Samples"
            mnemonic="S"
            lastMenu="true"
    />
    <menuitem
            type="javax.swing.JMenu"
            name="Help"
            mnemonic="H"
    >
        <menuitem
                name="Help Topics"
                mnemonic="T"
                accelerator="F1"
                tooltip="Display Help Topics"
                icon="images/help.png"
                actionCommand="Help"
                separator="true"
                toolButton="javax.swing.JButton"
        />
        <menuitem
                name="About"
                mnemonic="A"
                tooltip="About STED"
                icon="images/sted.gif"
                actionCommand="About"
                last="true"
                toolButton="javax.swing.JButton"
        />
    </menuitem>
</menuitems>


